mode: development
media_root: media
media_url: /media
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
meta:
    nodemeta: meta.yaml
    ga_tracking_code: UA-21972762-1
urlcleaner:
    index_file_names:
        - index.html
    strip_extensions:
        - html
