mode: development
media_root: media
media_url: /media
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin

meta:
    nodemeta: meta.yaml
    ga_tracking_code: UA-21972762-1
