mode: development
media_root: media
media_url: /media
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.GrouperPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
    - hyde.ext.plugins.text.TextlinksPlugin
    - hash.HashPlugin
meta:
    nodemeta: meta.yaml
    ga_tracking_code: UA-21972762-1
context:
    data:
        menu:
            - name: Home
              type: page
              url: index.html
            - name: About
              type: page
              url: about.html
            - name: Blog
              type: node
              url: blog/
            - name: Speaking
              type: page
              url: speaking.html
        website_url: http://merlin.rebrovic.net
    providers:
        featured_posts: featured_posts.yaml

sorter:
    latest:
        attr: meta.created
        reverse: True

grouper:
    category:
        sorter: latest
        description: Blog category
        groups:
            - name: Tech
              description: Technology and programming
            - name: Design
              description: Sketching, visual arts and design
            - name: Personal
              description: Personal thoughts
            - name: People
              description: Psychology, education and motivation
            - name: Travel
              description: World exploration

hasher:
    - media/css/style.css
    - media/js/app.js
